### ISSUE TITLE
Dependency error?

### ISSUE THREAD

**Issue by gh21usr** [ecphp/eu-login-api-authentication-bundle#11]
Hello,

After an apparent successful installation of the bundle, cache:clear returns the error:

> In BaseNode.php line 557:
>                                                                              
> A dynamic value is not compatible with a "Symfony\Component\Config\Definiti  
> on\EnumNode" node type at path "eu_login_api_authentication.environment".

Is this because of my project, or is it because of another dependency (which I do not know how to solve)?

Thank you

**Comment by gh21usr** [comment]
Okay, it has to do with _config/packages/dev/eu_login_api_authentication.yaml_ . 

The environment property doesn't like to take the value from .env

> environment: "%env(EULOGIN_ENV)%"

but if I change that directly to:

> environment: acceptance

it works.

**Comment by drupol** [comment]
Hi,

The only valid values are defined here: https://github.com/ecphp/eu-login-api-authentication-bundle/blob/master/src/DependencyInjection/Configuration.php#L32

Closing the issue, feel free to reopen it if you feel that something is not fixed for you.
