### ISSUE TITLE
How to add local attributes to the user object?

### ISSUE THREAD

**Issue by gh21usr** [ecphp/eu-login-api-authentication-bundle#14]
Hello,

How can I add extra attributes to the user object?

So, http://localhost:8000/api/user returns: 
{
    "sub": "username",
    "active": true
}

Me, I would like to add some grants from the database, for instance: canAddComment, canDeleteComment. These are defined in the local database. 
I believe I need to add a "grants" attribute to the EuLoginApiAuthenticationUser storage property, right? So that the user object would look like:

{
    "sub": "username",
    "active": true,
    "grants": {           
                "canAddComment": true,
                "canDeleteComment": false     
    }     
}

But how can I add this? 
From what I see in EcPhp\EuLoginApiAuthenticationBundle\Security\EuLoginApiAuthenticationGuardAuthenticator, I can do it in getUser() method, when calling loadUserByUsernameAndPayload().
But this is in vendor, and we should not make changes in vendor.
Also, I cannot extend the EuLoginApiAuthenticationGuardAuthenticator class, because it is final class.

Can you please advise?

Thank you

**Comment by drupol** [comment]
Dear @gh21usr,

Does it helped ? Can we close the issue ?

**Comment by gh21usr** [comment]
Dear drupol, I cannot remember what I did, but you can close the ticket, thank you.

**Comment by drupol** [comment]
Thanks.
